// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.19.4
// source: product.proto

package service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ProdService_GetProductStock_FullMethodName       = "/service.ProdService/GetProductStock"
	ProdService_UpdateProductStock_FullMethodName    = "/service.ProdService/UpdateProductStock"
	ProdService_GetProductStockStream_FullMethodName = "/service.ProdService/GetProductStockStream"
	ProdService_WoShiNiMaStream_FullMethodName       = "/service.ProdService/WoShiNiMaStream"
)

// ProdServiceClient is the client API for ProdService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProdServiceClient interface {
	GetProductStock(ctx context.Context, in *ProductRequest, opts ...grpc.CallOption) (*ProductResponse, error)
	// 客户端流
	UpdateProductStock(ctx context.Context, opts ...grpc.CallOption) (ProdService_UpdateProductStockClient, error)
	// 服务端流
	GetProductStockStream(ctx context.Context, in *ProductRequest, opts ...grpc.CallOption) (ProdService_GetProductStockStreamClient, error)
	// 双向流
	WoShiNiMaStream(ctx context.Context, opts ...grpc.CallOption) (ProdService_WoShiNiMaStreamClient, error)
}

type prodServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProdServiceClient(cc grpc.ClientConnInterface) ProdServiceClient {
	return &prodServiceClient{cc}
}

func (c *prodServiceClient) GetProductStock(ctx context.Context, in *ProductRequest, opts ...grpc.CallOption) (*ProductResponse, error) {
	out := new(ProductResponse)
	err := c.cc.Invoke(ctx, ProdService_GetProductStock_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *prodServiceClient) UpdateProductStock(ctx context.Context, opts ...grpc.CallOption) (ProdService_UpdateProductStockClient, error) {
	stream, err := c.cc.NewStream(ctx, &ProdService_ServiceDesc.Streams[0], ProdService_UpdateProductStock_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &prodServiceUpdateProductStockClient{stream}
	return x, nil
}

type ProdService_UpdateProductStockClient interface {
	Send(*ProductRequest) error
	CloseAndRecv() (*ProductResponse, error)
	grpc.ClientStream
}

type prodServiceUpdateProductStockClient struct {
	grpc.ClientStream
}

func (x *prodServiceUpdateProductStockClient) Send(m *ProductRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *prodServiceUpdateProductStockClient) CloseAndRecv() (*ProductResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(ProductResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *prodServiceClient) GetProductStockStream(ctx context.Context, in *ProductRequest, opts ...grpc.CallOption) (ProdService_GetProductStockStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &ProdService_ServiceDesc.Streams[1], ProdService_GetProductStockStream_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &prodServiceGetProductStockStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ProdService_GetProductStockStreamClient interface {
	Recv() (*ProductResponse, error)
	grpc.ClientStream
}

type prodServiceGetProductStockStreamClient struct {
	grpc.ClientStream
}

func (x *prodServiceGetProductStockStreamClient) Recv() (*ProductResponse, error) {
	m := new(ProductResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *prodServiceClient) WoShiNiMaStream(ctx context.Context, opts ...grpc.CallOption) (ProdService_WoShiNiMaStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &ProdService_ServiceDesc.Streams[2], ProdService_WoShiNiMaStream_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &prodServiceWoShiNiMaStreamClient{stream}
	return x, nil
}

type ProdService_WoShiNiMaStreamClient interface {
	Send(*ProductRequest) error
	Recv() (*ProductResponse, error)
	grpc.ClientStream
}

type prodServiceWoShiNiMaStreamClient struct {
	grpc.ClientStream
}

func (x *prodServiceWoShiNiMaStreamClient) Send(m *ProductRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *prodServiceWoShiNiMaStreamClient) Recv() (*ProductResponse, error) {
	m := new(ProductResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ProdServiceServer is the server API for ProdService service.
// All implementations must embed UnimplementedProdServiceServer
// for forward compatibility
type ProdServiceServer interface {
	GetProductStock(context.Context, *ProductRequest) (*ProductResponse, error)
	// 客户端流
	UpdateProductStock(ProdService_UpdateProductStockServer) error
	// 服务端流
	GetProductStockStream(*ProductRequest, ProdService_GetProductStockStreamServer) error
	// 双向流
	WoShiNiMaStream(ProdService_WoShiNiMaStreamServer) error
	mustEmbedUnimplementedProdServiceServer()
}

// UnimplementedProdServiceServer must be embedded to have forward compatible implementations.
type UnimplementedProdServiceServer struct {
}

func (UnimplementedProdServiceServer) GetProductStock(context.Context, *ProductRequest) (*ProductResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProductStock not implemented")
}
func (UnimplementedProdServiceServer) UpdateProductStock(ProdService_UpdateProductStockServer) error {
	return status.Errorf(codes.Unimplemented, "method UpdateProductStock not implemented")
}
func (UnimplementedProdServiceServer) GetProductStockStream(*ProductRequest, ProdService_GetProductStockStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method GetProductStockStream not implemented")
}
func (UnimplementedProdServiceServer) WoShiNiMaStream(ProdService_WoShiNiMaStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method WoShiNiMaStream not implemented")
}
func (UnimplementedProdServiceServer) mustEmbedUnimplementedProdServiceServer() {}

// UnsafeProdServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProdServiceServer will
// result in compilation errors.
type UnsafeProdServiceServer interface {
	mustEmbedUnimplementedProdServiceServer()
}

func RegisterProdServiceServer(s grpc.ServiceRegistrar, srv ProdServiceServer) {
	s.RegisterService(&ProdService_ServiceDesc, srv)
}

func _ProdService_GetProductStock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProdServiceServer).GetProductStock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProdService_GetProductStock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProdServiceServer).GetProductStock(ctx, req.(*ProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProdService_UpdateProductStock_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ProdServiceServer).UpdateProductStock(&prodServiceUpdateProductStockServer{stream})
}

type ProdService_UpdateProductStockServer interface {
	SendAndClose(*ProductResponse) error
	Recv() (*ProductRequest, error)
	grpc.ServerStream
}

type prodServiceUpdateProductStockServer struct {
	grpc.ServerStream
}

func (x *prodServiceUpdateProductStockServer) SendAndClose(m *ProductResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *prodServiceUpdateProductStockServer) Recv() (*ProductRequest, error) {
	m := new(ProductRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _ProdService_GetProductStockStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ProductRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ProdServiceServer).GetProductStockStream(m, &prodServiceGetProductStockStreamServer{stream})
}

type ProdService_GetProductStockStreamServer interface {
	Send(*ProductResponse) error
	grpc.ServerStream
}

type prodServiceGetProductStockStreamServer struct {
	grpc.ServerStream
}

func (x *prodServiceGetProductStockStreamServer) Send(m *ProductResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _ProdService_WoShiNiMaStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ProdServiceServer).WoShiNiMaStream(&prodServiceWoShiNiMaStreamServer{stream})
}

type ProdService_WoShiNiMaStreamServer interface {
	Send(*ProductResponse) error
	Recv() (*ProductRequest, error)
	grpc.ServerStream
}

type prodServiceWoShiNiMaStreamServer struct {
	grpc.ServerStream
}

func (x *prodServiceWoShiNiMaStreamServer) Send(m *ProductResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *prodServiceWoShiNiMaStreamServer) Recv() (*ProductRequest, error) {
	m := new(ProductRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ProdService_ServiceDesc is the grpc.ServiceDesc for ProdService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProdService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "service.ProdService",
	HandlerType: (*ProdServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetProductStock",
			Handler:    _ProdService_GetProductStock_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UpdateProductStock",
			Handler:       _ProdService_UpdateProductStock_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "GetProductStockStream",
			Handler:       _ProdService_GetProductStockStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "WoShiNiMaStream",
			Handler:       _ProdService_WoShiNiMaStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "product.proto",
}
